Заявки на доработку ПО/Controllers/SoftwareController.cs
using Заявки_на_доработку_ПО.Classes;

namespace Заявки_на_доработку_ПО.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;

    public class SoftwareController : Controller
    {
        private readonly SoftwareTicketsContext _context; // замените ApplicationDbContext на ваш DbContext

        public SoftwareController(SoftwareTicketsContext context) // замените ApplicationDbContext на ваш DbContext
        {
            this._context = context;
        }

        // GET: Software
        public async Task<IActionResult> Index(int pageNumber = 1)
        {
            int pageSize = 10;
            var software = this._context.Software.AsQueryable(); // ваша логика может быть здесь

            return this.View(await PaginatedList<Software>.CreateAsync(software, pageNumber, pageSize));
        }


        // GET: Software/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var software = await this._context.Software
                .FirstOrDefaultAsync(m => m.Id == id);
            if (software == null)
            {
                return this.NotFound();
            }

            return this.View(software);
        }

        // GET: Software/Create
        public IActionResult Create()
        {
            return this.View();
        }

        // POST: Software/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Название")] Software software)
        {
            if (this.ModelState.IsValid)
            {
                this._context.Add(software);
                await this._context.SaveChangesAsync();
                return this.RedirectToAction(nameof(Index));
            }
            return this.View(software);
        }

        // GET: Software/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var software = await this._context.Software.FindAsync(id);
            if (software == null)
            {
                return this.NotFound();
            }
            return this.View(software);
        }

        // POST: Software/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Название")] Software software)
        {
            if (id != software.Id)
            {
                return this.NotFound();
            }

            if (this.ModelState.IsValid)
            {
                try
                {
                    this._context.Update(software);
                    await this._context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!this.SoftwareExists(software.Id))
                    {
                        return this.NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return this.RedirectToAction(nameof(Index));
            }
            return this.View(software);
        }

        // GET: Software/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var software = await this._context.Software
                .FirstOrDefaultAsync(m => m.Id == id);
            if (software == null)
            {
                return this.NotFound();
            }

            return this.View(software);
        }

        // POST: Software/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var software = await this._context.Software.FindAsync(id);
            this._context.Software.Remove(software);
            await this._context.SaveChangesAsync();
            return this.RedirectToAction(nameof(Index));
        }


        private bool SoftwareExists(int id)
        {
            return this._context.Software.Any(e => e.Id == id);
        }
    }

}

Заявки на доработку ПО/Controllers/TicketsController.cs
namespace Заявки_на_доработку_ПО.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.EntityFrameworkCore;
    using System.Linq;
    using System.Threading.Tasks;
    using Заявки_на_доработку_ПО.Classes;

    public class TicketsController : Controller
    {
        private readonly SoftwareTicketsContext _context;

        public TicketsController(SoftwareTicketsContext context)
        {
            this._context = context;
        }

        [HttpGet]
        public IActionResult GetSoftwareByName(string term)
        {
            var softwareItems = this._context.Software.Where(s => s.Название.Contains(term));
            return this.Json(softwareItems);
        }


        // GET: Tickets
        public async Task<IActionResult> Index(int pageNumber = 1, int pageSize = 10)
        {
            //var tickets = this._context.Tickets;
            var tickets = this._context.Tickets.Include(t => t.ПО).AsNoTracking();
            var pagedData = await PaginatedList<Ticket>.CreateAsync(tickets.AsNoTracking(), pageNumber, pageSize);
            return this.View(pagedData);
        }

        // GET: Tickets/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var ticket = await this._context.Tickets
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ticket == null)
            {
                return this.NotFound();
            }

            return this.View(ticket);
        }

        // GET: Tickets/Create
        public IActionResult Create()
        {
            var softwareItems = this._context.Software;
            if (softwareItems == null || !softwareItems.Any())
            {
                throw new Exception("No software items found");
            }

            this.ViewBag.IdПО = new SelectList(softwareItems, "Id", "Название");
            return this.View();
        }


        // POST: Tickets/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,IdПО,Название,Email,Описание,ДатаОкончанияРазработки")] Ticket ticket)
        {
            if (!this.ModelState.IsValid)
            {
                var errors = this.ModelState
                    .Where(x => x.Value.Errors.Count > 0)
                    .Select(x => new { x.Key, x.Value.Errors })
                    .ToArray();

                // здесь вы можете просмотреть ошибки, используя отладчик или выводя их в консоль/лог
            }

            if (this.ModelState.IsValid)
            {
                this._context.Add(ticket);
                await this._context.SaveChangesAsync();
                return this.RedirectToAction(nameof(Index));
            }
            this.ViewBag.IdПО = new SelectList(this._context.Software, "Id", "Название", ticket.IdПО);
            return this.View(ticket);
        }

        // GET: Tickets/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var ticket = await this._context.Tickets.FindAsync(id);
            if (ticket == null)
            {
                return this.NotFound();
            }

            // Добавьте следующие две строки
            var softwareItems = this._context.Software;
            this.ViewBag.IdПО = new SelectList(softwareItems, "Id", "Название", ticket.IdПО);

            return this.View(ticket);
        }


        // POST: Tickets/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,IdПО,Название,Email,Описание,ДатаОкончанияРазработки")] Ticket ticket)
        {
            if (id != ticket.Id)
            {
                return this.NotFound();
            }

            if (this.ModelState.IsValid)
            {
                try
                {
                    this._context.Update(ticket);
                    await this._context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!this.TicketExists(ticket.Id))
                    {
                        return this.NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return this.RedirectToAction(nameof(Index));
            }
            this.ViewBag.IdПО = new SelectList(this._context.Software, "Id", "Название", ticket.IdПО);
            return this.View(ticket);
        }


        // GET: Tickets/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var ticket = await this._context.Tickets
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ticket == null)
            {
                return this.NotFound();
            }

            return this.View(ticket);
        }

        // POST: Tickets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ticket = await this._context.Tickets.FindAsync(id);
            this._context.Tickets.Remove(ticket);
            await this._context.SaveChangesAsync();
            return this.RedirectToAction(nameof(Index));
        }

        private bool TicketExists(int id)
        {
            return this._context.Tickets.Any(e => e.Id == id);
        }
    }

}

Заявки на доработку ПО/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Заявки_на_доработку_ПО</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <style>
        /* Добавлены дополнительные стили */
        .navbar-dark .navbar-nav .nav-link:hover {
            color: #fff;
            background-color: #343a40;
        }

        .footer {
            text-align: center;
        }
    </style>
    <!-- ✅ Load CSS file for Select2 -->
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css"
          rel="stylesheet" />

    <!-- ✅ load jQuery ✅ -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
            crossorigin="anonymous"></script>

    <!-- ✅ load JS for Select2 ✅ -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"
            integrity="sha512-2ImtlRlf2VVmiGZsjm9bEyhjGW4dU7B6TNwh/hx/iSByxNENtj3WVE6o/9Lj4TJeVXPi4bnOIMXFIJJAeufa0A=="
            crossorigin="anonymous"
            referrerpolicy="no-referrer"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Доработка ПО</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Tickets" asp-action="Index">Просмотреть заявки</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Software" asp-action="Index">Просмотреть приложения</a>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Заявки на доработку ПО
        </div>
    </footer>
    <script>
        $(document).ready(function () {
            $('.select2').select2();
        });
    </script>


    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>